name: Metrics
on:
  schedule: [{ cron: "0 */12 * * *" }]
  workflow_dispatch:
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: BretasArthur1
          template: classic
          base: ""
          filename: github-metrics.svg
          config_timezone: America/Sao_Paulo

          
          plugin_notable: yes
          plugin_notable_from: all              
          plugin_notable_types: pull_request, issue, commit
          plugin_notable_indepth: yes            
          plugin_notable_repositories: 5         
