name: Metrics

on:
  schedule: [{ cron: "0 */12 * * *" }]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: BretasArthur1
          template: classic
          base: ""
          filename: github-metrics.svg
          config_timezone: America/Sao_Paulo

          # mostra os repositórios contribuídos
          plugin_repositories: yes
