name: Metrics
on:
  schedule: [{cron: "0 */12 * * *"}] # Atualiza a cada 12h
  workflow_dispatch: # Permite rodar manualmente

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: BretasArthur1
          template: classic
          base: ""
          config_timezone: America/Sao_Paulo
          plugin_repositories: yes
